dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages: 
    - doxygen
    - graphviz

script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen Doxyfile

deploy:
  provider: pages
    skip-cleanup: true
    local_dir: /html
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
     branch: master
  
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujacksonrr3:$BINTRAY_API_KEY "https://api.bintray.com/content/jacksonrr3/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  

